# Generated by Django 6.0.2 on 2026-02-27 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoLavagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=1000, unique=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("disponivel", models.BooleanField(default=True)),
            ],
            options={
                "unique_together": {("data", "hora")},
            },
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=1000)),
                ("email", models.EmailField(max_length=1000)),
                ("whatsapp", models.CharField(max_length=1000)),
                ("placa", models.CharField(max_length=1000)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "horario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamento.horario",
                    ),
                ),
                (
                    "tipo_lavagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="agendamento.tipolavagem",
                    ),
                ),
            ],
        ),
    ]
