# Generated by Django 6.0.2 on 2026-02-26 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Horario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Agendamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=1000)),
                ("email", models.EmailField(max_length=1000)),
                ("whatsapp", models.CharField(max_length=1000)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agendamento.horario",
                    ),
                ),
            ],
        ),
    ]
