# Generated by Django 6.0.2 on 2026-02-26 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendamento",
            old_name="whatsapp",
            new_name="telefone",
        ),
        migrations.RemoveField(
            model_name="agendamento",
            name="email",
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="horario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="agendamento.horario"
            ),
        ),
    ]
