# Generated by Django 6.0.2 on 2026-02-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0002_rename_whatsapp_agendamento_telefone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agendamento",
            old_name="telefone",
            new_name="whatsapp",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="email",
            field=models.EmailField(default="sememail@email.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="agendamento",
            name="placa",
            field=models.CharField(default="sememail@email.com", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="nome",
            field=models.CharField(max_length=100),
        ),
    ]
