# Generated by Django 6.0.2 on 2026-02-27 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agendamento", "0003_rename_telefone_agendamento_whatsapp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoLavagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=1000, unique=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ativo", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name="horario",
            unique_together={("data", "hora")},
        ),
        migrations.AddField(
            model_name="agendamento",
            name="tipo_lavagem",
            field=models.ForeignKey(
                default="teste@teste.com",
                on_delete=django.db.models.deletion.PROTECT,
                to="agendamento.tipolavagem",
            ),
            preserve_default=False,
        ),
    ]
